apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bank-site-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bank-site-chart
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 15s
