apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bank-site-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bank-site-chart
      app.kubernetes.io/instance: bank-site
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 30s

