apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-system
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: kube-dns
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
  - port: metrics
    interval: 15s
