apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bank-site-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: bank-site
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 15s

