apiVersion: v1
kind: Service
metadata:
  name: bank-site-service
spec:
  selector:
    app: bank-site
  type: NodePort
  ports:
    - protocol: TCP
      port: 90
      targetPort: 90
      nodePort: 30080
